name: quatrex
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alabaster=0.7.16
  - alsa-lib=1.2.12
  - annotated-types=0.6.0
  - babel=2.14.0
  - black=24.8.0
  - blas=1.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2024.7.4
  - cairo=1.18.0
  - certifi=2024.7.4
  - cffi=1.16.0
  - cfgv=3.4.0
  - charset-normalizer=3.3.2
  - click=8.1.7
  - colorama=0.4.6
  - contourpy=1.2.1
  - coverage=7.6.1
  - cuda-version=11.4
  - cudatoolkit=11.4.3
  - cupy=13.2.0
  - cupy-core=13.2.0
  - cycler=0.11.0
  - dbus=1.13.18
  - distlib=0.3.8
  - docutils=0.21.2
  - double-conversion=3.3.0
  - expat=2.6.2
  - fastrlock=0.8.2
  - filelock=3.13.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=2.001
  - font-ttf-source-code-pro=2.030
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-anaconda=1
  - fonts-conda-ecosystem=1
  - fonttools=4.51.0
  - freetype=2.12.1
  - glib=2.80.3
  - glib-tools=2.80.3
  - graphite2=1.3.14
  - harfbuzz=9.0.0
  - icu=75.1
  - identify=2.5.5
  - idna=3.7
  - imagesize=1.4.1
  - iniconfig=1.1.1
  - isort=5.13.2
  - jinja2=3.1.4
  - keyutils=1.6.1
  - kiwisolver=1.4.4
  - krb5=1.21.3
  - lcms2=2.16
  - ld_impl_linux-64=2.38
  - lerc=4.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libclang-cpp18.1=18.1.8
  - libclang13=18.1.8
  - libcups=2.3.3
  - libdeflate=1.21
  - libdrm=2.4.122
  - libedit=3.1.20230828
  - libexpat=2.6.2
  - libffi=3.4.4
  - libgcc-ng=14.1.0
  - libgfortran-ng=14.1.0
  - libgfortran5=14.1.0
  - libglib=2.80.3
  - libgomp=14.1.0
  - libiconv=1.17
  - libjpeg-turbo=3.0.3
  - liblapack=3.9.0
  - libllvm18=18.1.8
  - libnsl=2.0.1
  - libopenblas=0.3.27
  - libpciaccess=0.18
  - libpng=1.6.43
  - libpq=16.4
  - libsqlite=3.46.0
  - libstdcxx-ng=14.1.0
  - libtiff=4.6.0
  - libuuid=2.38.1
  - libwebp-base=1.4.0
  - libxcb=1.16
  - libxcrypt=4.4.36
  - libxkbcommon=1.7.0
  - libxml2=2.12.7
  - libxslt=1.1.39
  - libzlib=1.3.1
  - markupsafe=2.1.3
  - matplotlib=3.9.2
  - matplotlib-base=3.9.2
  - mpi=1.0
  - mpi4py=3.1.6
  - mpich=4.2.0
  - mypy_extensions=1.0.0
  - mysql-common=8.3.0
  - mysql-libs=8.3.0
  - ncurses=6.4
  - nodeenv=1.7.0
  - numpy=2.1.0
  - openjpeg=2.5.2
  - openssl=3.3.1
  - packaging=24.1
  - pathspec=0.10.3
  - pcre2=10.44
  - pillow=10.4.0
  - pip=24.2
  - pixman=0.43.2
  - platformdirs=3.10.0
  - pluggy=1.0.0
  - pre-commit=3.8.0
  - pre_commit=3.8.0
  - pthread-stubs=0.3
  - pybind11-abi=4
  - pycparser=2.21
  - pydantic=2.8.2
  - pydantic-core=2.20.1
  - pygments=2.18.0
  - pyparsing=3.0.9
  - pyside6=6.7.2
  - pysocks=1.7.1
  - pytest=7.4.4
  - pytest-cov=5.0.0
  - pytest-mpi=0.6
  - python=3.11.8
  - python-dateutil=2.9.0post0
  - python_abi=3.11
  - pytz=2024.1
  - pyyaml=6.0.1
  - qhull=2020.2
  - qt6-main=6.7.2
  - readline=8.2
  - requests=2.32.3
  - ruff=0.6.1
  - scipy=1.14.0
  - setuptools=72.1.0
  - six=1.16.0
  - snowballstemmer=2.2.0
  - sphinx=8.0.2
  - sphinxcontrib-applehelp=1.0.2
  - sphinxcontrib-devhelp=1.0.2
  - sphinxcontrib-htmlhelp=2.0.0
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.3
  - sphinxcontrib-serializinghtml=1.1.10
  - sqlite=3.31.1
  - tk=8.6.13
  - toml=0.10.2
  - tomli=2.0.1
  - tornado=6.4.1
  - typing-extensions=4.11.0
  - typing_extensions=4.11.0
  - tzdata=2024a
  - ukkonen=1.0.1
  - unicodedata2=15.1.0
  - urllib3=2.2.2
  - virtualenv=20.26.1
  - wayland=1.23.0
  - wheel=0.43.0
  - xcb-util=0.4.1
  - xcb-util-cursor=0.1.4
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xkeyboard-config=2.42
  - xorg-kbproto=1.0.7
  - xorg-libice=1.1.1
  - xorg-libsm=1.2.4
  - xorg-libx11=1.8.9
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.11
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.4.6
  - yaml=0.2.5
  - zlib=1.3.1
  - zstd=1.5.6